import {createClient} from '@supabase/supabase-js';
import {config} from './config.js';
import {escapeHTML as e,safeURL,renderPackage,subject,newPackage,snapshot,recipients,normalizeImport,mime} from './core.js';
import {mailboxes,disconnectMail,connectGoogle,connectMicrosoft,createDraft} from './mail.js';
import './style.css';
const db=createClient(config.url,config.key),$=s=>document.querySelector(s);
const state={user:null,workspaces:[],workspace:null,models:[],packages:[],templates:[],current:null,view:'packages',dirty:false,query:'',market:'',busy:false};
let previewURL;
const clone=x=>structuredClone(x);
const notice=(message,error=false)=>{const n=$('#notice');n.textContent=message;n.className=error?'error':'visible';clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.className='',8000);};
function check(result){if(result.error)throw result.error;return result.data;}
async function run(fn){if(state.busy)return;state.busy=true;try{await fn();}catch(err){notice(err.message||String(err),true);}finally{state.busy=false;}}
function dirty(){state.dirty=true;const n=$('#save-state');if(n)n.textContent='Unsaved changes';}
function canLeave(){return !state.dirty||confirm('Discard your unsaved changes?');}
function field(label,id,value='',type='text',extra=''){return `<label>${label}<input id="${id}" type="${type}" value="${e(value)}" ${extra}></label>`;}
function area(label,id,value='',extra=''){return `<label>${label}<textarea id="${id}" ${extra}>${e(value)}</textarea></label>`;}
function closeModal(){$('#modal').close();$('#modal').innerHTML='';}
function modal(html){$('#modal').innerHTML=`<button class="close" data-action="close" aria-label="Close dialog">×</button>${html}`;$('#modal').showModal();}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function header(){return `<header><a class="wordmark" href="#">CHEZ LES<br><span>MANNEQUINS</span></a><div class="header-title">Submission Manager <small>Agency workspace</small></div><div class="account">${e(state.user.email)}<button data-action="logout" class="quiet">Sign out</button></div></header>`;}
function auth(){state.user=null;$('#app').innerHTML=`<main class="auth"><div class="wordmark">CHEZ LES<br><span>MANNEQUINS</span></div><p class="eyebrow">SUBMISSION MANAGER</p><h1>Your roster.<br>Your point of view.</h1><p class="muted">Build model packages together. Keep your mailbox yours.</p><form id="auth-form">${field('Email','email','','email','required autocomplete="email"')}${field('Password','password','','password','required minlength="8" autocomplete="current-password"')}<div class="actions"><button class="primary" type="submit">Sign in</button><button type="button" data-action="signup">Create account</button></div></form><p class="muted small">Use your team’s invite code after creating your account.</p></main>`;}
async function loadWorkspaces(){state.workspaces=check(await db.from('clm_workspaces').select('*').order('created_at'));state.workspace=state.workspaces.find(x=>x.id===state.workspace?.id)||state.workspaces[0]||null;if(state.workspace)await loadData();render();}
async function loadData(){const w=state.workspace.id;const results=await Promise.all([db.from('clm_models').select('*').eq('workspace_id',w).eq('archived',false).order('name'),db.from('clm_packages').select('*').eq('workspace_id',w).order('updated_at',{ascending:false}),db.from('clm_templates').select('*').eq('workspace_id',w).order('name')]);[state.models,state.packages,state.templates]=results.map(check);}
function render(){
 if(!state.user)return auth();
 if(!state.workspace){$('#app').innerHTML=header()+`<main class="onboard"><p class="eyebrow">GET STARTED</p><h1>A place for your team.</h1><div class="two"><section class="panel"><h2>Create a workspace</h2>${field('Workspace name','workspace-name','Chez Les Mannequins')}<button class="primary" data-action="create-workspace">Create workspace</button></section><section class="panel"><h2>Join your team</h2>${field('Single-use invite code','invite-code')}<button data-action="join-workspace">Join workspace</button></section></div></main>`;return;}
 $('#app').innerHTML=header()+`<div class="shell"><aside><label class="small">Workspace<select id="workspace-select">${state.workspaces.map(w=>`<option value="${w.id}" ${w.id===state.workspace.id?'selected':''}>${e(w.name)}</option>`).join('')}</select></label><nav>${[['packages','Packages'],['models','Models'],['templates','Templates'],['settings','Settings & team']].map(([v,l])=>`<button data-nav="${v}" class="${v===state.view?'active':''}">${l}</button>`).join('')}</nav><div class="aside-note">Choose the talent.<br>Make it personal.<br><strong>Save as a draft.</strong></div></aside><main class="workspace" id="workspace"></main></div>`;
 if(state.view==='packages')renderPackages();if(state.view==='models')renderModels();if(state.view==='templates')renderTemplates();if(state.view==='settings')renderSettings();
}
function renderPackages(){
 const p=state.current;
 if(!p){$('#workspace').innerHTML=`<div class="page-head"><div><p class="eyebrow">YOUR SELECTIONS</p><h1>Packages</h1></div><button class="primary" data-action="new-package">New package <span>＋</span></button></div><p class="muted">Shared with ${e(state.workspace.name)}. Mailbox drafts remain personal.</p><div class="package-grid">${state.packages.length?state.packages.map(p=>`<button class="package-card" data-open="${p.id}"><span class="eyebrow">${e(p.event||'Untitled event')}</span><h2>${e(p.brand||'Untitled brand')}</h2><div class="mini-portraits">${(p.body.models||[]).slice(0,4).map(m=>m.selectedMedia?.find(x=>x.type!=='video')?.url).filter(safeURL).map(u=>`<img src="${e(u)}" alt="" loading="lazy">`).join('')}</div><span class="muted">${p.body.models?.length||0} models · Version ${p.version}</span><small>Updated ${new Date(p.updated_at).toLocaleDateString()}</small></button>`).join(''):`<div class="empty"><h2>Your next selection starts here.</h2><p>Create a package and choose models from the shared roster.</p></div>`}</div>`;return;}
 const b=p.body;
 $('#workspace').innerHTML=`<div class="page-head"><div><button class="quiet" data-action="back">← All packages</button><h1 id="package-title">${e(p.brand||'New package')}</h1><span id="save-state" class="muted">${state.dirty?'Unsaved changes':p.id?'Saved · Version '+p.version:'Not saved yet'}</span></div><div class="actions"><button data-action="duplicate">Duplicate</button><button class="primary" data-action="save">Save package</button></div></div><div class="builder"><section><div class="panel"><div class="two">${field('Event','event',p.event)}${field('Brand','brand',p.brand)}</div><div class="subject">Subject <strong id="subject">${e(subject(p))||'Event | Brand'}</strong></div>${area('Recipients (one draft per address)','recipients',b.recipients||'')}<label>Apply a saved template<select id="apply-template"><option value="">Choose template</option>${state.templates.map(t=>`<option value="${t.id}">${e(t.name)}</option>`).join('')}</select></label>${area('Your opening text','intro',b.intro)}${area('Your closing text','closing',b.closing)}<p class="hint">Add a link with [link text](https://…). Text stays exactly as you write it.</p><details><summary>Layout</summary>${field('Image width (pixels)','photoWidth',b.photoWidth,'number','min="160" max="600"')}<label class="check"><input id="measurements" type="checkbox" ${b.measurements!==false?'checked':''}> Show measurements</label></details></div><div class="section-head"><h2>Selected models <span class="count">${b.models.length}</span></h2><button data-action="choose-models">Add models</button></div><div id="selected">${b.models.length?b.models.map((m,i)=>selectedModel(m,i)).join(''):'<div class="empty compact">Choose models to begin your selection.</div>'}</div></section><section class="preview-column"><div class="panel preview-panel"><div class="section-head"><h2>Draft preview</h2><button data-action="preview">Refresh preview</button></div><iframe id="preview" title="Email draft preview" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer"></iframe><div class="actions"><button class="primary" data-action="draft-dialog">Create mailbox drafts</button><button data-action="export-html">Export HTML</button><button data-action="export-eml">Export EML</button></div><p class="hint">Nothing is sent. Review and edit each draft in your mailbox.</p><button class="quiet" data-action="draft-history">View draft history</button></div></section></div>`;
 updatePreview();
}
function selectedModel(m,i){const model=state.models.find(x=>x.id===m.id);const availableMedia=[...new Map([...(model?.media||[]),...(m.selectedMedia||[])].map(x=>[x.url,x])).values()];return `<article class="selected-card"><div class="section-head"><h3>${e(m.name)}</h3><div class="actions"><button data-move="${i}" data-step="-1" aria-label="Move ${e(m.name)} up" ${i===0?'disabled':''}>↑</button><button data-move="${i}" data-step="1" aria-label="Move ${e(m.name)} down" ${i===state.current.body.models.length-1?'disabled':''}>↓</button><button data-remove="${i}">Remove</button></div></div><div class="media-options">${availableMedia.map(x=>`<label><input type="checkbox" data-media="${i}" data-url="${e(x.url)}" ${m.selectedMedia.some(a=>a.url===x.url)?'checked':''}>${x.type==='video'?'<span>Video</span>':`<img src="${e(safeURL(x.url))}" alt="${e(m.name)}" loading="lazy">`}</label>`).join('')||'<span class="hint">Add media in Models.</span>'}</div><label>Text insert<select data-insert="${i}"><option value="">Choose reusable text</option>${(model?.texts||[]).map(t=>`<option value="${e(t.id)}">${e(t.label)}</option>`).join('')}</select></label><label class="check"><input type="checkbox" data-enabled="${i}" ${m.textEnabled!==false?'checked':''}> Include text</label><label>Text for this package<textarea data-text="${i}">${e(m.text)}</textarea></label></article>`;}
function updatePreview(){if(!$('#preview'))return;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(new Blob([renderPackage(state.current)],{type:'text/html'}));$('#preview').src=previewURL;}
async function savePackage(){const pending=state.current;const before=JSON.stringify(pending);const p=clone(pending);if(!p.event.trim()||!p.brand.trim())throw Error('Add the event and brand before saving.');if(!p.body.models.length)throw Error('Choose at least one model.');let saved;if(p.id){saved=check(await db.from('clm_packages').update({event:p.event,brand:p.brand,body:p.body}).eq('id',p.id).eq('version',p.version).select().maybeSingle());if(!saved)throw Error('This package was changed by another agent. Duplicate your work to preserve it, then reopen the current version.');}else saved=check(await db.from('clm_packages').insert({workspace_id:p.workspace_id,event:p.event,brand:p.brand,body:p.body}).select().single());const editedDuringSave=JSON.stringify(pending)!==before;state.current=editedDuringSave?{...saved,event:pending.event,brand:pending.brand,body:pending.body}:saved;state.dirty=editedDuringSave;await loadData();renderPackages();notice(editedDuringSave?'Saved. Your newer edits still need saving.':'Package saved.');return saved;}
function renderModels(){const q=state.query.toLowerCase(),markets=[...new Set(state.models.map(m=>m.market).filter(Boolean))].sort();const models=state.models.filter(m=>(!state.market||m.market===state.market)&&[m.name,m.market,m.measurements].join(' ').toLowerCase().includes(q));$('#workspace').innerHTML=`<div class="page-head"><div><p class="eyebrow">SHARED ROSTER</p><h1>Models</h1></div><div class="actions"><button data-action="import">Import roster</button><button data-action="export-roster">Export roster</button><button class="primary" data-action="new-model">Add model</button></div></div><div class="filters">${field('Search roster','model-search',state.query)}<label>Market<select id="market-filter"><option value="">All markets</option>${markets.map(m=>`<option ${state.market===m?'selected':''}>${e(m)}</option>`).join('')}</select></label><span class="muted">${models.length} models</span></div><div class="model-grid">${models.map(m=>`<button class="model-card" data-model="${m.id}">${m.media.find(x=>x.type!=='video')?`<img src="${e(safeURL(m.media.find(x=>x.type!=='video').url))}" alt="${e(m.name)}" loading="lazy">`:'<div class="placeholder">CLM</div>'}<h2>${e(m.name)}</h2><p>${e(m.market)}</p><small>${m.texts.length} text inserts · ${m.media.length} media</small></button>`).join('')||'<div class="empty"><h2>Your shared roster is ready.</h2><p>Add a model or import a roster JSON export.</p></div>'}</div>`;}
let editingModel;
function editModel(id){editingModel=id?clone(state.models.find(m=>m.id===id)):{name:'',market:'',measurements:'',profile_url:'',media:[],texts:[]};drawModel();}
function collectModel(){if(!$('#model-name'))return;Object.assign(editingModel,{name:$('#model-name').value,market:$('#model-market').value,measurements:$('#model-measurements').value,profile_url:$('#model-profile').value});document.querySelectorAll('[data-text-label]').forEach(n=>{const t=editingModel.texts[Number(n.dataset.textLabel)];t.label=n.value;t.text=$(`[data-text-body="${n.dataset.textLabel}"]`).value;});}
function drawModel(){modal(`<h2>${editingModel.id?'Edit model':'Add model'}</h2><div class="two">${field('Name','model-name',editingModel.name)}${field('Market','model-market',editingModel.market)}</div>${area('Measurements','model-measurements',editingModel.measurements)}${field('Portfolio link','model-profile',editingModel.profile_url,'url')}<h3>Media library</h3><div class="media-options">${editingModel.media.map((x,i)=>`<div>${x.type==='video'?'<span>Video</span>':`<img src="${e(safeURL(x.url))}" alt="${e(editingModel.name)}" loading="lazy">`}<button data-delete-media="${i}">Remove</button></div>`).join('')}</div>${field('Image, GIF or video HTTPS link','media-url','','url')}<label>Media type<select id="media-type"><option value="image">Image / GIF</option><option value="video">Video link</option></select></label><div class="actions"><button data-action="add-media">Add link</button><label class="upload">Upload media<input id="upload-media" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/quicktime"></label></div><p class="hint">Uploaded portfolio media is accessible to anyone with its link so it can display in emails. Use direct image URLs for images; Drive sharing pages work as text links.</p><div class="section-head"><h3>Reusable text inserts</h3><button data-action="add-text">Add text</button></div>${editingModel.texts.map((t,i)=>`<div class="text-edit"><label>Label<input data-text-label="${i}" value="${e(t.label)}"></label><label>Your text<textarea data-text-body="${i}">${e(t.text)}</textarea></label><button data-delete-text="${i}">Remove text</button></div>`).join('')}<p class="hint">Embed media links using [View video](https://…). Choose a text insert in any package, then edit or disable it there.</p><div class="actions"><button class="primary" data-action="save-model">Save model</button>${editingModel.id?'<button data-action="archive-model">Archive model</button>':''}</div>`);}
async function saveModel(){collectModel();const m=editingModel;if(!m.name.trim())throw Error('Model name required.');if(m.profile_url&&!safeURL(m.profile_url))throw Error('Use an HTTPS portfolio URL.');if(m.name.trim().toLowerCase()==='molly'&&!/new york/i.test(m.market))throw Error('Only Molly from New York belongs in this roster.');const value={workspace_id:state.workspace.id,name:m.name.trim(),market:m.market,measurements:m.measurements,profile_url:m.profile_url,media:m.media,texts:m.texts};if(m.id){const r=check(await db.from('clm_models').update(value).eq('id',m.id).eq('version',m.version).select().maybeSingle());if(!r)throw Error('Another agent edited this model. Copy your changes, close and reopen the model.');}else check(await db.from('clm_models').insert(value));closeModal();await loadData();renderModels();notice('Model saved. Existing packages keep their saved selections and text.');}
function renderTemplates(){$('#workspace').innerHTML=`<div class="page-head"><div><p class="eyebrow">REUSABLE LAYOUTS</p><h1>Templates</h1></div><button class="primary" data-action="new-template">New template</button></div><p class="muted">Templates store your own opening text, closing text and layout. Applying one leaves selected models intact.</p><div class="package-grid">${state.templates.map(t=>`<button class="package-card" data-template="${t.id}"><h2>${e(t.name)}</h2><span>Version ${t.version}</span></button>`).join('')||'<div class="empty">Create your first template.</div>'}</div>`;}
let editingTemplate;
function editTemplate(id){editingTemplate=id?clone(state.templates.find(t=>t.id===id)):{name:'',body:{intro:'',closing:'',photoWidth:360,measurements:true}};const t=editingTemplate;modal(`<h2>Template</h2>${field('Name','template-name',t.name)}${area('Your opening text','template-intro',t.body.intro)}${area('Your closing text','template-closing',t.body.closing)}${field('Image width','template-width',t.body.photoWidth,'number','min="160" max="600"')}<label class="check"><input id="template-measurements" type="checkbox" ${t.body.measurements!==false?'checked':''}> Show measurements</label><button class="primary" data-action="save-template">Save template</button>`);}
function oauthSettings(){try{return JSON.parse(localStorage.getItem('clm-submission-oauth')||'{}');}catch{return {};}}
function renderSettings(){const o=oauthSettings();$('#workspace').innerHTML=`<div class="page-head"><div><p class="eyebrow">YOUR WORKSPACE</p><h1>Settings & team</h1></div></div><div class="two"><section class="panel"><h2>Connected mailboxes</h2><p class="muted">Connect one or more accounts. Connections last for this browser session and are never shared with your team.</p><div id="mailbox-list">${mailboxes().map(m=>`<p>${e(m.email)} <span class="pill">${m.provider==='google'?'Gmail':'Outlook'}</span></p>`).join('')||'<p class="muted">No mailbox connected.</p>'}</div><div class="actions"><button data-action="connect-google">Connect Gmail</button><button data-action="connect-microsoft">Connect Outlook</button><button data-action="disconnect">Disconnect all</button></div><details open><summary>Mailbox application setup</summary>${field('Google OAuth web client ID','google-id',o.google||'')}${field('Microsoft application client ID','microsoft-id',o.microsoft||'')}<button data-action="save-oauth">Save client IDs</button><p class="hint">These are public application IDs, not passwords or client secrets. Your administrator registers this app’s origin with Google or Microsoft before first use.</p><p class="hint">Google origin: <code>${e(location.origin)}</code><br>Microsoft SPA redirect: <code>${e(new URL('./auth.html',location.href).href)}</code></p></details></section><section class="panel"><h2>Team access</h2><p class="muted">An administrator can create a single-use invite code, valid for two days. Give it only to the person joining your team.</p><button data-action="invite">Create invite code</button><div id="invite-result"></div><hr>${field('Invite code for another workspace','join-code')}<button data-action="join-another">Join workspace</button></section></div>`;}
function chooseModels(){modal(`<h2>Add models</h2>${field('Search models','choose-search')}<div id="choose-list"></div>`);drawChoices('');}
function drawChoices(q){$('#choose-list').innerHTML=state.models.filter(m=>[m.name,m.market].join(' ').toLowerCase().includes(q.toLowerCase())).map(m=>`<button class="choice" data-select="${m.id}" ${state.current.body.models.some(x=>x.id===m.id)?'disabled':''}><strong>${e(m.name)}</strong><span>${e(m.market)}</span><span>${state.current.body.models.some(x=>x.id===m.id)?'Added':'＋ Add'}</span></button>`).join('')||'<p>No matching models. Add your roster in Models.</p>';}
function draftDialog(){if(!state.current.id||state.dirty)throw Error('Save the package before creating mailbox drafts.');const addresses=recipients(state.current.body.recipients);const boxes=mailboxes();modal(`<h2>Create mailbox drafts</h2><p>${addresses.length} recipient${addresses.length===1?'':'s'}. A separate draft will be created for each recipient in each selected mailbox.</p>${boxes.map(m=>`<label class="check"><input type="checkbox" name="mailbox" value="${e(m.key)}">${e(m.email)} (${m.provider==='google'?'Gmail':'Outlook'})</label>`).join('')||'<p>Connect a mailbox in Settings first.</p>'}<p class="hint">Saved subject: ${e(subject(state.current))}</p><button class="primary" data-action="create-drafts" ${boxes.length?'':'disabled'}>Create drafts</button><div id="draft-results" aria-live="polite"></div>`);}
async function createDrafts(){const keys=[...document.querySelectorAll('[name="mailbox"]:checked')].map(n=>n.value);if(!keys.length)throw Error('Select at least one mailbox.');const p=state.current,addresses=recipients(p.body.recipients);const fresh=check(await db.from('clm_packages').select('version').eq('id',p.id).single());if(fresh.version!==p.version)throw Error('The saved package has changed. Reopen it before creating drafts.');$('[data-action="create-drafts"]').disabled=true;const results=$('#draft-results');
 for(const key of keys)for(const recipient of addresses){const m=mailboxes().find(x=>x.key===key);const row=document.createElement('p');results.append(row);row.textContent=`${m.email} → ${recipient}: working…`;let reserved;
 try{
 if(m.expires<Date.now()+30000)throw Error('Reconnect this mailbox in Settings.');
 const r=await db.from('clm_drafts').insert({package_id:p.id,package_version:p.version,mailbox:m.email,recipient,provider:m.provider}).select().single();if(r.error?.code==='23505')throw Error('Already requested for this saved version. Check draft history and your mailbox; no duplicate was created.');reserved=check(r);
 const remote=await createDraft(key,p,recipient);if(!remote.id)throw Error('The mailbox did not return a draft ID.');
 check(await db.from('clm_drafts').update({status:'created',provider_id:remote.id}).eq('id',reserved.id));row.textContent=`${m.email} → ${recipient}: draft created.`;
 }catch(err){if(reserved)await db.from('clm_drafts').update({status:'uncertain'}).eq('id',reserved.id);row.textContent=`${m.email} → ${recipient}: ${err.message}${reserved?' Check your mailbox before trying again.':''}`;}
 }
}
const actions={
 close:closeModal,
 signup:async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password){$('#auth-form').reportValidity();throw Error('Enter your email and a password of at least 8 characters, then choose Create account.');}if(!$('#auth-form').reportValidity())return;const result=check(await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}));if(result.session){state.user=result.user;await loadWorkspaces();}else notice('Account created. Confirm using the email link, then return here and sign in.');},
 logout:async()=>{if(!canLeave())return;check(await db.auth.signOut());disconnectMail();state.current=null;state.workspace=null;state.models=[];state.packages=[];state.templates=[];state.dirty=false;closeModal();auth();},
 'create-workspace':async()=>{const id=check(await db.rpc('clm_create_workspace',{n:$('#workspace-name').value}));state.workspace={id};await loadWorkspaces();},
 'join-workspace':async()=>{const id=check(await db.rpc('clm_join_workspace',{t:$('#invite-code').value.trim()}));state.workspace={id};await loadWorkspaces();},
 'join-another':async()=>{const id=check(await db.rpc('clm_join_workspace',{t:$('#join-code').value.trim()}));state.workspace={id};state.current=null;await loadWorkspaces();},
 'new-package':()=>{state.current=newPackage(state.workspace.id);state.dirty=false;renderPackages();},
 back:async()=>{if(!canLeave())return;state.current=null;state.dirty=false;await loadData();renderPackages();},
 save:savePackage,
 duplicate:()=>{state.current=clone(state.current);delete state.current.id;delete state.current.version;delete state.current.updated_at;state.dirty=true;renderPackages();notice('Independent copy created. Save to add it to Packages.');},
 preview:updatePreview,
 'choose-models':chooseModels,
 'new-model':()=>editModel(),
 'add-text':()=>{collectModel();editingModel.texts.push({id:crypto.randomUUID(),label:'',text:''});drawModel();},
 'add-media':()=>{collectModel();const url=safeURL($('#media-url').value.trim());if(!url)throw Error('Use a public HTTPS URL.');if(!editingModel.media.some(x=>x.url===url))editingModel.media.push({id:crypto.randomUUID(),url,type:$('#media-type').value,label:''});drawModel();},
 'save-model':saveModel,
 'archive-model':async()=>{if(!confirm('Archive this model? Saved packages will keep their selected media and text.'))return;const r=check(await db.from('clm_models').update({archived:true}).eq('id',editingModel.id).eq('version',editingModel.version).select().maybeSingle());if(!r)throw Error('Model changed. Reopen it first.');closeModal();await loadData();renderModels();},
 'new-template':()=>editTemplate(),
 'save-template':async()=>{const t=editingTemplate,value={workspace_id:state.workspace.id,name:$('#template-name').value.trim(),body:{intro:$('#template-intro').value,closing:$('#template-closing').value,photoWidth:Number($('#template-width').value),measurements:$('#template-measurements').checked}};if(!value.name)throw Error('Template name required.');if(t.id){const r=check(await db.from('clm_templates').update(value).eq('id',t.id).eq('version',t.version).select().maybeSingle());if(!r)throw Error('Template changed. Reopen it first.');}else check(await db.from('clm_templates').insert(value));closeModal();await loadData();renderTemplates();},
 'save-oauth':()=>{localStorage.setItem('clm-submission-oauth',JSON.stringify({google:$('#google-id').value.trim(),microsoft:$('#microsoft-id').value.trim()}));disconnectMail();notice('Client IDs saved. Connect a mailbox to continue.');renderSettings();},
 'connect-google':async()=>{await connectGoogle(oauthSettings().google);renderSettings();notice('Gmail connected.');},
 'connect-microsoft':async()=>{await connectMicrosoft(oauthSettings().microsoft);renderSettings();notice('Outlook connected.');},
 disconnect:()=>{disconnectMail();renderSettings();},
 invite:async()=>{const r=check(await db.from('clm_invites').insert({workspace_id:state.workspace.id}).select().single());$('#invite-result').innerHTML=`<p>Single-use code:</p><code>${e(r.token)}</code><p class="hint">Expires ${new Date(r.expires_at).toLocaleString()}</p>`;},
 'draft-dialog':draftDialog,
 'create-drafts':createDrafts,
 'draft-history':async()=>{if(!state.current.id)throw Error('Save your package first.');const rows=check(await db.from('clm_drafts').select('*').eq('package_id',state.current.id).order('created_at',{ascending:false}));modal(`<h2>Your draft history</h2>${rows.map(r=>`<article class="history"><strong>${e(r.recipient)}</strong><p>${e(r.mailbox)} · Version ${r.package_version} · ${e(r.status)}</p>${r.provider_id?`<small>Draft ID: ${e(r.provider_id)}</small>`:'<small>Check your mailbox before requesting another copy.</small>'}</article>`).join('')||'<p>No drafts requested yet.</p>'}`);},
 'export-html':()=>download('model-package.html',renderPackage(state.current),'text/html'),
 'export-eml':()=>{const list=recipients(state.current.body.recipients);if(list.length!==1)throw Error('For EML export, enter one recipient. Mailbox creation supports multiple recipients.');download('model-package.eml','X-Unsent: 1\r\n'+mime(state.current,list[0]),'message/rfc822');},
 'export-roster':()=>download('clm-roster.json',JSON.stringify(state.models,null,2)),
 import:()=>modal(`<h2>Import roster</h2><p>Import a roster JSON export. Existing models are never overwritten. Review the model count before adding.</p><label>Roster JSON<input id="import-file" type="file" accept=".json,application/json"></label><button data-action="reference-roster">Load existing agency snapshot</button><p class="hint">The snapshot is the older standalone builder’s roster. Review it before use. Browser-only CRM changes require a current JSON export.</p><div id="import-review"></div>`),
 'reference-roster':async()=>{const r=await fetch(new URL('../reference-roster.json',import.meta.url));if(!r.ok)throw Error('Roster snapshot could not be loaded.');reviewImport(await r.json());},
 'confirm-import':async()=>{if(!pendingImport.length)throw Error('No new models to add.');check(await db.from('clm_models').insert(pendingImport.map(m=>({...m,workspace_id:state.workspace.id}))));closeModal();await loadData();renderModels();notice('Roster imported.');}
};
let pendingImport=[];
function reviewImport(data){const rows=normalizeImport(Array.isArray(data)?data:data.models);const seen=new Set(state.models.map(m=>`${m.name.toLowerCase()}|${m.market.toLowerCase()}`));pendingImport=rows.filter(m=>{const k=`${m.name.toLowerCase()}|${m.market.toLowerCase()}`;if(seen.has(k))return false;seen.add(k);return true;});$('#import-review').innerHTML=`<h3>${pendingImport.length} new models</h3><p>${rows.length-pendingImport.length} duplicates skipped.</p><div class="import-names">${pendingImport.map(m=>`<p>${e(m.name)} · ${e(m.market)}</p>`).join('')}</div><button class="primary" data-action="confirm-import">Add these models</button>`;}
$('#app').addEventListener('submit',event=>{if(event.target.id!=='auth-form')return;event.preventDefault();run(async()=>{const r=check(await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value}));state.user=r.user;await loadWorkspaces();});});
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;
 run(async()=>{
 if(b.dataset.action){await actions[b.dataset.action]?.();return;}
 if(b.dataset.nav){if(!canLeave())return;state.current=null;state.dirty=false;state.view=b.dataset.nav;await loadData();render();return;}
 if(b.dataset.open){state.current=clone(state.packages.find(p=>p.id===b.dataset.open));state.dirty=false;renderPackages();}
 if(b.dataset.model)editModel(b.dataset.model);
 if(b.dataset.template)editTemplate(b.dataset.template);
 if(b.dataset.select){const m=state.models.find(m=>m.id===b.dataset.select);if(!state.current.body.models.some(x=>x.id===m.id))state.current.body.models.push(snapshot(m));dirty();drawChoices($('#choose-search').value);renderPackages();}
 if(b.dataset.remove!==undefined){state.current.body.models.splice(Number(b.dataset.remove),1);dirty();renderPackages();}
 if(b.dataset.move!==undefined){const i=Number(b.dataset.move),j=i+Number(b.dataset.step),a=state.current.body.models;if(j>=0&&j<a.length)[a[i],a[j]]=[a[j],a[i]];dirty();renderPackages();}
 if(b.dataset.deleteMedia!==undefined){collectModel();editingModel.media.splice(Number(b.dataset.deleteMedia),1);drawModel();}
 if(b.dataset.deleteText!==undefined){collectModel();editingModel.texts.splice(Number(b.dataset.deleteText),1);drawModel();}
 });
});
document.addEventListener('input',event=>{const n=event.target;
 if(n.id==='choose-search')drawChoices(n.value);
 if(n.id==='model-search'){state.query=n.value;const pos=n.selectionStart;renderModels();$('#model-search').focus();$('#model-search').setSelectionRange(pos,pos);}
 if(!state.current)return;
 if(['event','brand'].includes(n.id)){state.current[n.id]=n.value;$('#subject').textContent=subject(state.current);$('#package-title').textContent=state.current.brand||'New package';dirty();}
 if(['intro','closing','recipients','photoWidth'].includes(n.id)){state.current.body[n.id]=n.id==='photoWidth'?Number(n.value):n.value;dirty();}
 if(n.dataset.text!==undefined){state.current.body.models[Number(n.dataset.text)].text=n.value;dirty();}
});
document.addEventListener('change',event=>run(async()=>{const n=event.target;
 if(n.id==='workspace-select'){if(!canLeave()){render();return;}state.workspace=state.workspaces.find(w=>w.id===n.value);state.current=null;state.dirty=false;await loadData();render();}
 if(n.id==='market-filter'){state.market=n.value;renderModels();}
 if(n.id==='apply-template'&&n.value){if(!confirm('Apply this template’s text and layout? Selected models will stay in place.')){n.value='';return;}const b=state.templates.find(t=>t.id===n.value).body;Object.assign(state.current.body,clone(b));dirty();renderPackages();}
 if(n.id==='measurements'){state.current.body.measurements=n.checked;dirty();}
 if(n.dataset.enabled!==undefined){state.current.body.models[Number(n.dataset.enabled)].textEnabled=n.checked;dirty();}
 if(n.dataset.insert!==undefined&&n.value){const m=state.current.body.models[Number(n.dataset.insert)];m.text=state.models.find(x=>x.id===m.id).texts.find(t=>t.id===n.value).text;dirty();renderPackages();}
 if(n.dataset.media!==undefined){const m=state.current.body.models[Number(n.dataset.media)];if(n.checked){const x=state.models.find(x=>x.id===m.id)?.media.find(x=>x.url===n.dataset.url)||m.selectedMedia.find(x=>x.url===n.dataset.url);if(x&&!m.selectedMedia.some(a=>a.url===x.url))m.selectedMedia.push(clone(x));}else m.selectedMedia=m.selectedMedia.filter(x=>x.url!==n.dataset.url);dirty();}
 if(n.id==='upload-media'){const f=n.files?.[0];if(!f)return;if(f.size>15*1024*1024)throw Error('Maximum file size is 15 MB.');collectModel();const path=`${state.workspace.id}/${crypto.randomUUID()}.${f.name.split('.').pop().replace(/[^a-zA-Z0-9]/g,'')}`;check(await db.storage.from('clm-media').upload(path,f,{contentType:f.type,upsert:false}));const url=db.storage.from('clm-media').getPublicUrl(path).data.publicUrl;editingModel.media.push({id:crypto.randomUUID(),url,type:f.type.startsWith('video/')?'video':'image',label:f.name});drawModel();}
 if(n.id==='import-file'){const f=n.files?.[0];if(!f)return;if(f.size>10*1024*1024)throw Error('Roster JSON must be under 10 MB.');reviewImport(JSON.parse(await f.text()));}
}));
window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'&&state.user){disconnectMail();state.user=null;state.current=null;state.dirty=false;closeModal();auth();}});
$('#app').innerHTML='<main class="auth"><h1>Opening your workspace…</h1></main>';
run(async()=>{const {data,error}=await db.auth.getSession();if(error){auth();throw error;}state.user=data.session?.user||null;if(state.user)await loadWorkspaces();else auth();});
