-- Initial Chez Les Submission Manager schema. Apply once with Supabase migrations.
create schema if not exists clm_private;
revoke all on schema clm_private from public;
grant usage on schema clm_private to authenticated;
create table public.clm_workspaces(id uuid primary key default gen_random_uuid(), name text not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.clm_members(workspace_id uuid references public.clm_workspaces on delete cascade, user_id uuid references auth.users on delete cascade, role text not null check(role in ('admin','agent')), primary key(workspace_id,user_id));
create table public.clm_invites(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.clm_workspaces on delete cascade, token uuid not null unique default gen_random_uuid(), expires_at timestamptz not null default now()+interval '2 days', used_by uuid references auth.users);
create function clm_private.member(w uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.clm_members where workspace_id=w and user_id=auth.uid()) $$;
create function clm_private.admin(w uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.clm_members where workspace_id=w and user_id=auth.uid() and role='admin') $$;
create table public.clm_models(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.clm_workspaces on delete cascade, name text not null, market text not null default '', measurements text not null default '', profile_url text not null default '', media jsonb not null default '[]' check(jsonb_typeof(media)='array'), texts jsonb not null default '[]' check(jsonb_typeof(texts)='array'), archived boolean not null default false, version integer not null default 1, updated_at timestamptz not null default now());
create table public.clm_templates(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.clm_workspaces on delete cascade, name text not null, body jsonb not null default '{}', version integer not null default 1, updated_at timestamptz not null default now());
create table public.clm_packages(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.clm_workspaces on delete cascade, created_by uuid not null default auth.uid() references auth.users, event text not null default '', brand text not null default '', body jsonb not null default '{}', version integer not null default 1, updated_at timestamptz not null default now());
create table public.clm_drafts(id uuid primary key default gen_random_uuid(), package_id uuid not null references public.clm_packages, user_id uuid not null default auth.uid() references auth.users, package_version integer not null, mailbox text not null, recipient text not null, provider text not null check(provider in ('google','microsoft')), status text not null default 'pending' check(status in ('pending','created','uncertain','failed')), provider_id text, created_at timestamptz not null default now(), unique(package_id,package_version,user_id,mailbox,recipient));
create table public.clm_activity(id bigint generated always as identity primary key, workspace_id uuid not null references public.clm_workspaces, user_id uuid references auth.users, record_id uuid not null, action text not null, created_at timestamptz not null default now());
create function clm_private.stamp() returns trigger language plpgsql set search_path='' as $$ begin new.version=old.version+1; new.updated_at=now(); return new; end $$;
create function clm_private.log_change() returns trigger language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then return new; end if; insert into public.clm_activity(workspace_id,user_id,record_id,action) values(new.workspace_id,auth.uid(),new.id,tg_table_name||':'||tg_op); return new; end $$;
create function clm_private.create_workspace(n text) returns uuid language plpgsql security definer set search_path='' as $$ declare w uuid; begin if auth.uid() is null then raise exception 'Sign in first'; end if; if length(trim(n)) not between 1 and 120 then raise exception 'Workspace name required'; end if; insert into public.clm_workspaces(name,created_by) values(trim(n),auth.uid()) returning id into w; insert into public.clm_members values(w,auth.uid(),'admin'); return w; end $$;
create function public.clm_create_workspace(n text) returns uuid language sql security invoker set search_path='' as $$ select clm_private.create_workspace(n) $$;
create function clm_private.join_workspace(t uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare w uuid; begin if auth.uid() is null then raise exception 'Sign in first'; end if; update public.clm_invites set used_by=auth.uid() where token=t and used_by is null and expires_at>now() returning workspace_id into w; if w is null then raise exception 'Invite expired or already used'; end if; insert into public.clm_members values(w,auth.uid(),'agent') on conflict do nothing; return w; end $$;
create function public.clm_join_workspace(t uuid) returns uuid language sql security invoker set search_path='' as $$ select clm_private.join_workspace(t) $$;
revoke all on all functions in schema clm_private from public,anon;
grant execute on function clm_private.member(uuid),clm_private.admin(uuid),clm_private.create_workspace(text),clm_private.join_workspace(uuid) to authenticated;
revoke all on function public.clm_create_workspace(text),public.clm_join_workspace(uuid) from public,anon;
grant execute on function public.clm_create_workspace(text),public.clm_join_workspace(uuid) to authenticated;
alter table public.clm_workspaces enable row level security;
alter table public.clm_members enable row level security;
alter table public.clm_invites enable row level security;
alter table public.clm_drafts enable row level security;
alter table public.clm_activity enable row level security;
create policy workspace_read on public.clm_workspaces for select to authenticated using(clm_private.member(id));
create policy member_read on public.clm_members for select to authenticated using(clm_private.member(workspace_id));
create policy invite_admin on public.clm_invites for all to authenticated using(clm_private.admin(workspace_id)) with check(clm_private.admin(workspace_id));
create policy activity_read on public.clm_activity for select to authenticated using(clm_private.member(workspace_id));
create policy drafts_owner on public.clm_drafts for all to authenticated using(user_id=(select auth.uid()) and exists(select 1 from public.clm_packages p where p.id=package_id)) with check(user_id=(select auth.uid()) and exists(select 1 from public.clm_packages p where p.id=package_id));
do $$ declare t text; begin foreach t in array array['clm_models','clm_templates','clm_packages'] loop
execute format('alter table public.%I enable row level security',t);
execute format('create policy team_access on public.%I for all to authenticated using(clm_private.member(workspace_id)) with check(clm_private.member(workspace_id))',t);
execute format('create index on public.%I(workspace_id)',t);
execute format('create trigger stamp before update on public.%I for each row execute function clm_private.stamp()',t);
execute format('create trigger activity after insert or update on public.%I for each row execute function clm_private.log_change()',t);
end loop; end $$;
grant select on public.clm_workspaces,public.clm_members,public.clm_activity to authenticated;
grant select,insert,update,delete on public.clm_models,public.clm_templates,public.clm_packages,public.clm_invites,public.clm_drafts to authenticated;
revoke all on public.clm_workspaces,public.clm_members,public.clm_activity,public.clm_models,public.clm_templates,public.clm_packages,public.clm_invites,public.clm_drafts from anon;
create index on public.clm_members(user_id);
create index on public.clm_drafts(user_id);
create index on public.clm_activity(workspace_id);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('clm-media','clm-media',true,15728640,array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/quicktime']);
-- Public portfolio media is deliberately embeddable in client emails. Records remain private.
create policy media_insert on storage.objects for insert to authenticated with check(bucket_id='clm-media' and (storage.foldername(name))[1] in (select workspace_id::text from public.clm_members where user_id=(select auth.uid())));
create policy media_read on storage.objects for select to authenticated using(bucket_id='clm-media' and (storage.foldername(name))[1] in (select workspace_id::text from public.clm_members where user_id=(select auth.uid())));
